### PR TITLE
Manifest v2 and upgrade to v6.1.0

### LINKED ISSUE #27: Update to 6.0 ?
Hey Guys, could you please update this snipe-it for yunohost to 6.0? I would really like to use the new features of version 6.0 in my yunohost installation. 

Cheers and kind regards
Henri

### PR DESCRIPTION
**Pull request by Tagadda**
## Problem

- Fix #27 

## Solution

- manifest v2

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
!testme

**Comment by Tagadda** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by orhtej2** [comment]
!bookwormtestme

**Comment by Tagadda** [comment]
!testme

**Pull request merged**
